"""Recreate database schema

Revision ID: 5a175dc9c027
Revises: 9d36c92da392
Create Date: 2025-02-14 19:03:19.945697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a175dc9c027'
down_revision = '9d36c92da392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    with op.batch_alter_table('UserAnswers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('selected_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('numeric_answer', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_info', ['user_id'], ['id'])
        batch_op.drop_column('quiz_res_id')
        batch_op.drop_column('option_selected')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('option2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('option3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('option4', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('correct', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('answer_type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('answer_type')
        batch_op.drop_column('explanation')
        batch_op.drop_column('correct')
        batch_op.drop_column('option4')
        batch_op.drop_column('option3')
        batch_op.drop_column('option2')
        batch_op.drop_column('option1')

    with op.batch_alter_table('UserAnswers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_selected', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('quiz_res_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'option', ['option_selected'], ['id'])
        batch_op.create_foreign_key(None, 'QuizResult', ['quiz_res_id'], ['id'])
        batch_op.drop_column('timestamp')
        batch_op.drop_column('is_correct')
        batch_op.drop_column('numeric_answer')
        batch_op.drop_column('selected_answer')
        batch_op.drop_column('user_id')

    op.create_table('option',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('option', sa.VARCHAR(), nullable=True),
    sa.Column('correct', sa.BOOLEAN(), nullable=True),
    sa.Column('explanation', sa.VARCHAR(), nullable=True),
    sa.Column('answer_type', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
