"""Update question models

Revision ID: 9d36c92da392
Revises: d62ae52472ef
Create Date: 2025-02-13 09:24:33.018233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d36c92da392'
down_revision = 'd62ae52472ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('marks', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('numeric_answer', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tolerance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('tolerance')
        batch_op.drop_column('numeric_answer')
        batch_op.drop_column('marks')
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###
