"""Change quiz duration to Integer

Revision ID: d62ae52472ef
Revises: 
Create Date: 2025-02-13 00:43:05.233370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62ae52472ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Quiz', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
